/*
 +-----------------------------------------------------------+
 | Module Name: Response message module	                      |
 | Module Purpose: Manage the Response message in the response|
 +------------------------------------------------------------+
*/
'use strict';

module.exports = {
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    FORBIDDEN:"FORBIDDEN",
    REQUIRED_DATA: 'Please fill all required data.',
    SUCCESSFULLY_DONE: 'SUCCESS.',
    AUTH_FAIL:"Authentication Fail",
    EMAIL_IS_REQ:'Email Id is required',
    CORRECT_EMAIL_ID:'Please Enter Correct Email Id',
    PASS_IS_REQ:'Password is required',
    CORRECT_PASS:'Enter valid Password',
    ALREADY_EXISTS:'Already Exists',
    OTP_IS_REQ:'Otp is required',
    CORRECT_OTP:'Enter valid Otp',
    ROLE_IS_REQ:'Role is required',
    USER_IS_REQ:'User Id is required',
    WRONG:"Wrong Credentials",
    LOG_SUCCESS:"Successfully Logged In",
    USER_UPDATE_SUCCESS:"Profile Updated Successfully",
    USER_NOT_EXISTS:"User not Exists",
    EMAIL_NOT_EXISTS:'Please enter valid email.',
    WRONG_PASSWORD:"Please enter valid old password",
    PASSWORD_UPDATE:"Password updated successfully.",
    NOT_MODIFIED:'Profile not updated.',
    NEW_IS_REQ:'New Password is require',
    EMAIL_NOT_SEND:'Error while sending email.',
    PASSWORD_UPDATE_SUCCESS:'Password changed successfully.',
    PLAN_IS_REQ:'Plan is required.',
    ORGANIZER_NOT_FOUND:"Organizer  not Found.",
    ADD_MEMBER:"New Member Added.",
    ADD_PROFESSIONS:"New Professionals Added.",
    LIST_OF_PROFESSIONALS:"List of Professionals.",
    ORG_IS_REQ:"Organizer id is required.",
    MEMBER_EXISTS:"Membership with name all ready exists.",
    MEMBER_NOT_FOND:"Member not exists.",
    MEMBER_IS_REQ:"Membership Name is Required.",
    SERVICE_ADDED:"Service Added.",
    LOGOUT:"Logout Successfully.",
    CARD_DETAILS_NOT:'Card details not valid.',
    CARD_DETAIL:"Card Details.",
    INVALID_PHONE:"Invalid mobile number.",
    DELETE_CARD:"Card deleted successfully.",
    SIGNUP_SUCCESS:"Signup done successfully.",
    VERIFICATION_SUCCESSFULLY_DONE:"Otp successfully Verified.",
    OTP_SENDS:"Otp send Successfully.",
    USER_DETAIL:"User Details",
    USER_PLAN_UPDATE:"Plan updated Successfully.",
    INVALID_TOKEN:"INVALID TOKEN",
    PROVIDE_DATA:"Provide valid data.",
    ORGANIZER_IS_REQUIRED:"Organizer is required.",
    SPONSERS_ADDED:"Sponsers added successfully.",
    WRONG_PHONE:"Please enter valid mobile number.",
    SPONSER_IS_REQUIRED:"Sponsors Id is required.",
    SIGN_IN_WITH_VALID:"Enter valid email.",
    LIST_OF_SPONSERS:"List of Sponsers.",
    DETAIL_OF_SPONSER:"Detail of Sponser.",
    SPONSER_NOT_FOUND:"Sponser not Found.",
    SPONSER_EXISTS:"Sponsor Already Exists.",
    SPONSER_DELETE:"Sponsor deleted successfully.",
    NO_DATA_FOUND:"Sponser not exists.",
    CLUB_EXISTS:"Club already exists.",
    CLUB_ADDED:"Club added Successfully.",
    CLUB_EXISTS:"Club already exists.",
    CLUB_LIST:"List of club.",
    CLUB_NOT_FOUND:"Club not found.",
    CARD_NOT_FOUND:"Card details not found.",
    CARD_UPDATE:"Card details updated successfully.",
    CARD_DELET:"Card detail deleted successfully.",
    TERMS_ID_NOT:"Terms id not found.",
    TERMS_PRIVACY:"Terms and privacy policy.",
    TERMS_NOT_FOUND:"Terms for this role is not exists.",
    TERMS_MODIFIED:"Terms updated successfully.",
    CLUB_UPDATE:"Club detail updated successfully.",
    CLUB_DELETE:"Club deleted successfully."
    // INTERNAL_SERVER_ERROR: 'Internal server error.',
    // REQUIRED_DATA: 'Please fill all required data.',
    // SUCCESSFULLY_DONE: 'SUCCESS.',
    // EMAIL_IS_REQ:'Email Id is required',
    // CORRECT_EMAIL_ID:'Please Enter Correct Email Id',
    // PASS_IS_REQ:'Password is required',
    // CORRECT_PASS:'Enter Correct Password',
    // ALREADY_EXISTS:'Already Exists',
    // OTP_IS_REQ:'Otp is required',
    // CORRECT_OTP:'Enter Correct Otp',
    // ROLE_IS_REQ:'Role is required',
    // USER_IS_REQ:'User Id is required',
    // WRONG:"Wrong Credentials",
    // USER_UPDATE_SUCCESS:"Update Successfully",
    // USER_NOT_EXISTS:"User not Exists",
    // NEW_CONFIRM_INCORRECT: 'New and confirm password are not similar.',
    // OLD_PASSWORD_INCORRECT: 'Old password is incorrect.',
    // PASSWORD_UPDATE_SUCCESS: 'Password updated successfully.',
    // NOT_FOUND:"Data not found",
    // SOMETHING_WENT_WRONG:"Something went wrong"
};