const router=require('express').Router()
const mediaController = require('../webservices/controllers/media');
const AUTH=require('../middlewares/auth_handler')
router.get('/accessPlanMedia',AUTH.verifyToken,mediaController.accessPlanMedia)
router.post('/createTry',mediaController.createTry)
router.post('/createAlbum',AUTH.verifyToken,mediaController.createAlbum)
router.post('/getListOfMedia',AUTH.verifyToken,mediaController.getListOfMedia)
router.get('/getDetailofMedia',AUTH.verifyToken,mediaController.getDetailofMedia)
router.get('/likeMedia',AUTH.verifyToken,mediaController.likeMedia)
router.post('/getListOfMediaPlayer',AUTH.verifyToken,mediaController.getListOfMediaPlayer)
router.post('/commentMedia',AUTH.verifyToken,mediaController.commentMedia)
router.get("/getCommnet",AUTH.verifyToken,mediaController.getCommnet)
router.post('/mediaList',AUTH.verifyToken,mediaController.mediaList)
router.post('/editMedia',AUTH.verifyToken,mediaController.editMedia)
router.get('/deleteMedia',AUTH.verifyToken,mediaController.deleteMedia)
router.post('/editMediaNews',AUTH.verifyToken,mediaController.editMediaNews)
router.get('/mediaDelete',mediaController.mediaDelete)
module.exports=router 